// <auto-generated />
using System;
using FormBuilder.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormBuilder.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormBuilder.API.Models.FilledForm", b =>
                {
                    b.Property<int>("FormID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmasData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemplateID")
                        .HasColumnType("int");

                    b.HasKey("FormID");

                    b.HasIndex("TemplateID");

                    b.ToTable("FilledForms");
                });

            modelBuilder.Entity("FormBuilder.API.Models.TableRow", b =>
                {
                    b.Property<int>("RowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowID"));

                    b.Property<int>("FormID")
                        .HasColumnType("int");

                    b.Property<string>("RowData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RowID");

                    b.HasIndex("FormID");

                    b.ToTable("TableRows");
                });

            modelBuilder.Entity("FormBuilder.API.Models.Template", b =>
                {
                    b.Property<int>("TemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateID"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CuandoSeUsa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firmas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderFields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Objetivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proceso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuienLoLlena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TemplateID");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("FormBuilder.API.Models.FilledForm", b =>
                {
                    b.HasOne("FormBuilder.API.Models.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FormBuilder.API.Models.TableRow", b =>
                {
                    b.HasOne("FormBuilder.API.Models.FilledForm", "FilledForm")
                        .WithMany("TableRows")
                        .HasForeignKey("FormID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilledForm");
                });

            modelBuilder.Entity("FormBuilder.API.Models.FilledForm", b =>
                {
                    b.Navigation("TableRows");
                });
#pragma warning restore 612, 618
        }
    }
}
